### ISSUE TITLE
Using newer tensorflow versions

### ISSUE THREAD

**Issue by chrisroat** [hammerlab/flowdec#27]
Is there any active work on this project to upgrade to TF 2.0?  I'd be interested in helping out, if it's likely straightforward changes.

**Comment by eric-czech** [comment]
I don't believe anybody has tried that yet.  I imagine it would take little more than figuring out what has been deprecated / moved in [python/flowdec/restoration.py](python/flowdec/restoration.py) which shouldn't be too bad because other than the tf.fft functions, all the other TF operators are pretty vanilla (and likely well documented).
